# Séance du Mardi 05/03/2024

# Deep Learning

Deep Learning ou apprentissage profond. Le deep learning permet de faire le traitement du langage naturel via:

  - le NLP(Natural Language Processing) et 
  
  
  - le traitement d'images ou de vidéos à travers la computer vision(vision par ordinateur). 

In [1]:
import numpy as np

In [2]:
vector = np.array([1,2,3,8,17])

In [3]:
vector

array([ 1,  2,  3,  8, 17])

In [4]:
matrix = np.array([[1,2,3,8,17], [11,22,31,83,17]])

In [5]:
matrix

array([[ 1,  2,  3,  8, 17],
       [11, 22, 31, 83, 17]])

In [8]:
tensor = np.array(([[1,2,3,8,17], [11,22,31,83,17]], [[15,21,83,8,17], [14,22,31,63,97]]))

In [9]:
tensor

array([[[ 1,  2,  3,  8, 17],
        [11, 22, 31, 83, 17]],

       [[15, 21, 83,  8, 17],
        [14, 22, 31, 63, 97]]])

#### Une matrice est un ensemble de vecteurs 
#### Un tensor est un ensemble de matrices

- Lorsqu'une image est en blanc-noir, elle est en deux dimensions(longueur et largeur) mais lorsqu'elle est en couleur, elle est en trois dimensions doncplus la hauteur qui permet de gérer la couleur.


- Un modèle de deep learning est constitué de layers(couches).


#### Variables/Paramètres

x: Input ou entrée

w: Poids attribué à chaque entrée

In [ ]:
#Dans le cas de trois inputs
w1.x1  + w2.x2  + w3.x3

  - La fonction d'activation vous permet de calculer normalement la sortie/output.
    
    
  - L'output de la couche précédente est l'input de la couche qui suit cette dernière.


On a aussi la notion de hidden layers qui représente les couches cachées c'est-à-dire les couches entre la première et la dernière. La fonction d'activation se trouve au niveau de la toute dernière couche. Une autre fonction appelée fonction coût ou fonction de perte pour calculer l'erreur de prédiction. 

#### Notion de back propagation: 

Sur la base de la valeur de l'erreur, on actualise les valeurs de poids attribués à chaque variable et on performe encore le modèle. Lorsqu'on ajuste les poids et l'erreur est plus petite, on continue dans ce sens. Dans le cas contraire, on ajuste autrement.

Lorsqu'on essaie de calculer les erreurs de prédiction d'un modèle, on peut utiliser la fonction de la descente de gradient afin de trouver la plus petite erreur possible. 

La même chose se passe ici. On compare les prédictions du modèle par rapport aux données originales afin de conserver les variations et trouver la plus petite valeur possible.

Nous avons autant de noeuds au niveau de la première couche que de variables. Ce qui n'est pas forcément le cas au niveau des couches cachées.

#### Réseaux de neurones:

Les poids sont générés de manière aléatoire. Les inputs sont envoyés au niveau de la première couche. Il y a une combinaison entre les inputs et les poids aléatoires (avec un biais à chaque combinaison linéaire). L'output sera envoyé à la couche suivante. Pour obtenir une sortie, il y a des combinaisons linéaires(possible d'avoir des fonctions d'activation au niveau des couches cachées dans certaines architectures). La fonction d'activation est appliquée à la dernière couche(sur la combnaison linéaire obtenue à ce niveau) pour obtenir la prédiction. La fonction loss est ensuite appliquée pour calculer l'erreur de prédiction (loss_score). Après ça, il y a l'optimizer qui est responsable du sens que la descente de gradient va prendre. Il permet de savoir si le minimum est déjà atteint ou pas. 

Il faut toujours aller dans le sens opposé du gradient. Si le gradient est positif, il faut aller dans le sens inverse dans l'ajustement. Lorsqu'il est négatif, c'est que vous êtes sur le bon chemin.

Les poids liés à la plus petite erreur permettent donc de constituer notre modèle. On obtient donc des valeurs fixes des poids à la fin du processus.

#### Les notions d'epoch et de batch. 

- Batch: On donne au modèle un ensemble de lots pour qu'après ce nombre, le modèle montre ses performances et son bilan.
    
    - Epoch: Chaque fois que le modèle finit un batch
        
      - Taille de l'échantillon: Valeur du batch*Nbre d'epoch (Dans le cas où les valeurs de batch sont identiques)

#### Validation

Les données de validation font partie des données d'entraînement. 

Lorsqu'on a 4 batch, on prend 3 pour faire la validation et on change ainsi de suite pour faire passer tous les batch: c'est cette opération qui s'appelle la validation.

Ensuite, on applique le modèle sur les données du test set. 

## Fonctions d'activation

Il y a principalement 05 fonctions d'activation. La plus utilisée est la fonction sigmoïd.

- Sigmoïd: Pour une tâche de classification binaire(sortie entre 0 et 1). Dans ce cas, lorsque la valeur de la probabilité est inférieure à 0.5 ça s'approxime de 0 et lorsque la valeur est supérieure à 0.5 ça s'approxime de 1. Elle provient de la famille des fonctions softmax. 

- softmax: Lorsque la classification est multi-classe.

- relu: Utilisée au niveau des couches cachées.

- tan: Utilisée au niveau des couches cachées avec une sortie entre -1 et 1.

- Identité: Utilisée au niveau de la couche de sortie lorsqu'il s'agit de la régression.

sigmoid(x) = 1/(1+exp(-x)) ou softmax()

In [ ]:
exp(xi)/sum(exp(-xi)), 0...n-1 #softmax()

In [ ]:
relu(x) = max(0,x) #relu

In [ ]:
leaky_relu = x si x>0 et alpha.x sinon

In [ ]:
tan(x) = exp(x)-exp(-x)/exp(x)+exp(-x) #tan

In [ ]:
f(x) = x #Identité

In [22]:
def derivee(f,x, alpha = 0.00001):
    return round((f(x+alpha)-f(x))/alpha,4)#alpha peut être égal à 0.00001 ou autre.

#au lieu du round, on peut aussi utiliser np.trunc() pour réduire
#le nombre de chiffres après la virgule mais à un chiffre seulement.

In [23]:
f = lambda x : x**2

#def function(x):
#return 2*x**3-6*x+8

In [24]:
derivee(f,0)

0.0

In [25]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [26]:
sigmoid(0)

0.5

In [27]:
derivee(sigmoid,2)

0.105

In [ ]:
exp(-x)/(1+exp(-x)**2)

## Notion d'entropie

L'entropie est utilisée dans plusieurs domaines comme la thermodynamique et autres. C'est pour gérer l'incertitude ou le désordre en termes de classification. Elle permet de mesurer le degré d'incertitude sur la valeur que prendra la variable aléatoire.

Plus l'entropie est élevée, plus l'incertitude associée à la valeur de la variable aléatoire est élevée. La valeur de la variable aléatoire est difficile à prédire. 

L'idée c'est donc de minimiser la valeur de l'entropie.